 Додаток може виконати багато операцій між відкриттям та закриттям файлу. В будь-якому місці може статися помилка та додаток завершиться аварійно,
# не повернувши файловий дескриптор системі. Така поведінка, як вже згадувалося, небажана і може призводити до втрати даних.

# Щоб уникнути цього, можна укласти блок коду, в якому відбувається робота з файлом, у блок try ... except:

# fh = open('text.txt')
# try:
#     some_useful_function(fh)
# finally:
#     fh.close()
# В цьому прикладі ми викликали функцію some_useful_function всередині блоку try ... except і, якщо станеться виключення, 
# то обов'язково виконається блок finally, в якому файл буде закритий. Цей підхід гарантує, 
# що файловий дескриптор буде обов'язково повернений системі.

 Але такий підхід не надто елегантний та читабельний.
 Але такий підхід не надто елегантний та читабельний.
 Але такий підхід не надто елегантний та читабельний.
 Але такий підхід не надто елегантний та читабельний.
 Але такий підхід не надто елегантний та читабельний.
 Але такий підхід не надто елегантний та читабельний.
 Але такий підхід не надто елегантний та читабельний.